### ISSUE TITLE
Add NPM Provenance with publishing via GitHub Actions for releases 

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/deoxysii-js#38]
See:
 * https://docs.npmjs.com/generating-provenance-statements
 * https://github.blog/2023-04-19-introducing-npm-package-provenance/

Doing this will add a nice checkmark to the NPM page of the package, ideally this should be enabled on all publicly consumed NPM packages from Oasis Protocol.

This will also mean that there is a neat link between GitHub releases and NPM versions.

While the example below is for `npm`, publishing with provenance is also supported by `pnpm` .

```yaml
name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Suggested for `pnpm`

```yaml
name: Publish Package to npmjs
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true
      - name: Build package
        run: pnpm build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
```

Example:

![npm provenance on github](https://github.blog/wp-content/uploads/2023/04/introducing-npm-package-provenance.jpg?resize=1600%2C850)
